version: '3'

services:
  app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./database:/app/database
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    restart: unless-stopped 